# Timeout in seconds that Limine will use before automatically booting.
timeout: 0

# The entry name that will be displayed in the boot menu.
/Limine LearnixOS 
    protocol: limine
    path: boot():/boot/kernel

    # Userspace programs
    module_cmdline: init 
    module_path: boot():/boot/init

    module_cmdline: hello
    module_path: boot():/boot/hello
