#=== Kernel components ===#
option('sched', type: 'combo',
  choices: ['round_robin', 'lottery'],
  value: 'round_robin',
  description: 'Scheduler policy')

option('pmm', type: 'combo',
  choices: ['bitmap', 'linked_list'],
  value: 'bitmap',
  description: 'Physical memory manager')

option('kmalloc', type: 'combo',
  choices: [
    'watermark',  # a bump allocator that can't free
    'free_list'   # starting point into heap allocators
  ],
  value: 'free_list',
  description: 'Kernel heap manager')

#=== Security mitigations ===#
option('kpti', type: 'boolean',
  value: false,
  description: 'Enables Kernel Page Table Isolation (Meltdown mitigation)')
